Fix build on win64 with msys2-x86_64-20180531
- Changes from https://github.com/monero-project/monero-gui/commit/97cfbf5c50ac5f1c97ce631dd08b5c96c2824b08
- Add sodium link to prevent undefined reference to `crypto_verify_32' error
- Fix missing '/mingw64/bin/libicudt58.dll' by changing to icu v61